#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsgMuhendislik.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pisagorMuhendislikST")]
	public partial class pisagorDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCalisanCizelgesi(CalisanCizelgesi instance);
    partial void UpdateCalisanCizelgesi(CalisanCizelgesi instance);
    partial void DeleteCalisanCizelgesi(CalisanCizelgesi instance);
    partial void InsertCalisanEDevlet(CalisanEDevlet instance);
    partial void UpdateCalisanEDevlet(CalisanEDevlet instance);
    partial void DeleteCalisanEDevlet(CalisanEDevlet instance);
    partial void InsertCalisanlar(Calisanlar instance);
    partial void UpdateCalisanlar(Calisanlar instance);
    partial void DeleteCalisanlar(Calisanlar instance);
    partial void InsertCalisanlarDetay(CalisanlarDetay instance);
    partial void UpdateCalisanlarDetay(CalisanlarDetay instance);
    partial void DeleteCalisanlarDetay(CalisanlarDetay instance);
    partial void InsertFirmalar(Firmalar instance);
    partial void UpdateFirmalar(Firmalar instance);
    partial void DeleteFirmalar(Firmalar instance);
    partial void InsertFirmalarDetay(FirmalarDetay instance);
    partial void UpdateFirmalarDetay(FirmalarDetay instance);
    partial void DeleteFirmalarDetay(FirmalarDetay instance);
    partial void InsertGelenOdemeler(GelenOdemeler instance);
    partial void UpdateGelenOdemeler(GelenOdemeler instance);
    partial void DeleteGelenOdemeler(GelenOdemeler instance);
    partial void InsertHarcamalar(Harcamalar instance);
    partial void UpdateHarcamalar(Harcamalar instance);
    partial void DeleteHarcamalar(Harcamalar instance);
    partial void Insertİdri(İdri instance);
    partial void Updateİdri(İdri instance);
    partial void Deleteİdri(İdri instance);
    partial void InsertKullanıcılar(Kullanıcılar instance);
    partial void UpdateKullanıcılar(Kullanıcılar instance);
    partial void DeleteKullanıcılar(Kullanıcılar instance);
    partial void InsertMusteriler(Musteriler instance);
    partial void UpdateMusteriler(Musteriler instance);
    partial void DeleteMusteriler(Musteriler instance);
    partial void InsertMusterilerDetay(MusterilerDetay instance);
    partial void UpdateMusterilerDetay(MusterilerDetay instance);
    partial void DeleteMusterilerDetay(MusterilerDetay instance);
    #endregion
		
		public pisagorDBDataContext() : 
				base(global::PsgMuhendislik.Properties.Settings.Default.pisagorMuhendislikSTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public pisagorDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pisagorDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pisagorDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pisagorDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Yedek> Yedeks
		{
			get
			{
				return this.GetTable<Yedek>();
			}
		}
		
		public System.Data.Linq.Table<CalisanCizelgesi> CalisanCizelgesis
		{
			get
			{
				return this.GetTable<CalisanCizelgesi>();
			}
		}
		
		public System.Data.Linq.Table<CalisanEDevlet> CalisanEDevlets
		{
			get
			{
				return this.GetTable<CalisanEDevlet>();
			}
		}
		
		public System.Data.Linq.Table<Calisanlar> Calisanlars
		{
			get
			{
				return this.GetTable<Calisanlar>();
			}
		}
		
		public System.Data.Linq.Table<CalisanlarDetay> CalisanlarDetays
		{
			get
			{
				return this.GetTable<CalisanlarDetay>();
			}
		}
		
		public System.Data.Linq.Table<Firmalar> Firmalars
		{
			get
			{
				return this.GetTable<Firmalar>();
			}
		}
		
		public System.Data.Linq.Table<FirmalarDetay> FirmalarDetays
		{
			get
			{
				return this.GetTable<FirmalarDetay>();
			}
		}
		
		public System.Data.Linq.Table<GelenOdemeler> GelenOdemelers
		{
			get
			{
				return this.GetTable<GelenOdemeler>();
			}
		}
		
		public System.Data.Linq.Table<Harcamalar> Harcamalars
		{
			get
			{
				return this.GetTable<Harcamalar>();
			}
		}
		
		public System.Data.Linq.Table<İdri> İdris
		{
			get
			{
				return this.GetTable<İdri>();
			}
		}
		
		public System.Data.Linq.Table<Kullanıcılar> Kullanıcılars
		{
			get
			{
				return this.GetTable<Kullanıcılar>();
			}
		}
		
		public System.Data.Linq.Table<Musteriler> Musterilers
		{
			get
			{
				return this.GetTable<Musteriler>();
			}
		}
		
		public System.Data.Linq.Table<MusterilerDetay> MusterilerDetays
		{
			get
			{
				return this.GetTable<MusterilerDetay>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yedek")]
	public partial class Yedek
	{
		
		private int _ID;
		
		private string _Dosya;
		
		public Yedek()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dosya", DbType="NVarChar(255)")]
		public string Dosya
		{
			get
			{
				return this._Dosya;
			}
			set
			{
				if ((this._Dosya != value))
				{
					this._Dosya = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalisanCizelgesi")]
	public partial class CalisanCizelgesi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CalisanID;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private System.Nullable<double> _GunSayisi;
		
		private string _Aciklama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCalisanIDChanging(System.Nullable<int> value);
    partial void OnCalisanIDChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnGunSayisiChanging(System.Nullable<double> value);
    partial void OnGunSayisiChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    #endregion
		
		public CalisanCizelgesi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanID", DbType="Int")]
		public System.Nullable<int> CalisanID
		{
			get
			{
				return this._CalisanID;
			}
			set
			{
				if ((this._CalisanID != value))
				{
					this.OnCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanID = value;
					this.SendPropertyChanged("CalisanID");
					this.OnCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GunSayisi", DbType="Float")]
		public System.Nullable<double> GunSayisi
		{
			get
			{
				return this._GunSayisi;
			}
			set
			{
				if ((this._GunSayisi != value))
				{
					this.OnGunSayisiChanging(value);
					this.SendPropertyChanging();
					this._GunSayisi = value;
					this.SendPropertyChanged("GunSayisi");
					this.OnGunSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(250)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalisanEDevlet")]
	public partial class CalisanEDevlet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CalisanID;
		
		private string _TcNo;
		
		private string _Sifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCalisanIDChanging(System.Nullable<int> value);
    partial void OnCalisanIDChanged();
    partial void OnTcNoChanging(string value);
    partial void OnTcNoChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    #endregion
		
		public CalisanEDevlet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanID", DbType="Int")]
		public System.Nullable<int> CalisanID
		{
			get
			{
				return this._CalisanID;
			}
			set
			{
				if ((this._CalisanID != value))
				{
					this.OnCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanID = value;
					this.SendPropertyChanged("CalisanID");
					this.OnCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TcNo", DbType="NVarChar(11)")]
		public string TcNo
		{
			get
			{
				return this._TcNo;
			}
			set
			{
				if ((this._TcNo != value))
				{
					this.OnTcNoChanging(value);
					this.SendPropertyChanging();
					this._TcNo = value;
					this.SendPropertyChanged("TcNo");
					this.OnTcNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calisanlar")]
	public partial class Calisanlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _AdSoyad;
		
		private string _Telefon;
		
		private System.Nullable<System.DateTime> _IsBaslangicTarihi;
		
		private System.Nullable<decimal> _AlacakTutar;
		
		private string _CalismaSekli;
		
		private System.Nullable<System.DateTime> _SilinmeTarihi;
		
		private System.Nullable<int> _MaasGirisiDurum;
		
		private System.Nullable<bool> _Silme;
		
		private EntitySet<CalisanlarDetay> _CalisanlarDetays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAdSoyadChanging(string value);
    partial void OnAdSoyadChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnIsBaslangicTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnIsBaslangicTarihiChanged();
    partial void OnAlacakTutarChanging(System.Nullable<decimal> value);
    partial void OnAlacakTutarChanged();
    partial void OnCalismaSekliChanging(string value);
    partial void OnCalismaSekliChanged();
    partial void OnSilinmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSilinmeTarihiChanged();
    partial void OnMaasGirisiDurumChanging(System.Nullable<int> value);
    partial void OnMaasGirisiDurumChanged();
    partial void OnSilmeChanging(System.Nullable<bool> value);
    partial void OnSilmeChanged();
    #endregion
		
		public Calisanlar()
		{
			this._CalisanlarDetays = new EntitySet<CalisanlarDetay>(new Action<CalisanlarDetay>(this.attach_CalisanlarDetays), new Action<CalisanlarDetay>(this.detach_CalisanlarDetays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdSoyad", DbType="NVarChar(50)")]
		public string AdSoyad
		{
			get
			{
				return this._AdSoyad;
			}
			set
			{
				if ((this._AdSoyad != value))
				{
					this.OnAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._AdSoyad = value;
					this.SendPropertyChanged("AdSoyad");
					this.OnAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBaslangicTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> IsBaslangicTarihi
		{
			get
			{
				return this._IsBaslangicTarihi;
			}
			set
			{
				if ((this._IsBaslangicTarihi != value))
				{
					this.OnIsBaslangicTarihiChanging(value);
					this.SendPropertyChanging();
					this._IsBaslangicTarihi = value;
					this.SendPropertyChanged("IsBaslangicTarihi");
					this.OnIsBaslangicTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlacakTutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AlacakTutar
		{
			get
			{
				return this._AlacakTutar;
			}
			set
			{
				if ((this._AlacakTutar != value))
				{
					this.OnAlacakTutarChanging(value);
					this.SendPropertyChanging();
					this._AlacakTutar = value;
					this.SendPropertyChanged("AlacakTutar");
					this.OnAlacakTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalismaSekli", DbType="NVarChar(50)")]
		public string CalismaSekli
		{
			get
			{
				return this._CalismaSekli;
			}
			set
			{
				if ((this._CalismaSekli != value))
				{
					this.OnCalismaSekliChanging(value);
					this.SendPropertyChanging();
					this._CalismaSekli = value;
					this.SendPropertyChanged("CalismaSekli");
					this.OnCalismaSekliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilinmeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SilinmeTarihi
		{
			get
			{
				return this._SilinmeTarihi;
			}
			set
			{
				if ((this._SilinmeTarihi != value))
				{
					this.OnSilinmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._SilinmeTarihi = value;
					this.SendPropertyChanged("SilinmeTarihi");
					this.OnSilinmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaasGirisiDurum", DbType="Int")]
		public System.Nullable<int> MaasGirisiDurum
		{
			get
			{
				return this._MaasGirisiDurum;
			}
			set
			{
				if ((this._MaasGirisiDurum != value))
				{
					this.OnMaasGirisiDurumChanging(value);
					this.SendPropertyChanging();
					this._MaasGirisiDurum = value;
					this.SendPropertyChanged("MaasGirisiDurum");
					this.OnMaasGirisiDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silme", DbType="Bit")]
		public System.Nullable<bool> Silme
		{
			get
			{
				return this._Silme;
			}
			set
			{
				if ((this._Silme != value))
				{
					this.OnSilmeChanging(value);
					this.SendPropertyChanging();
					this._Silme = value;
					this.SendPropertyChanged("Silme");
					this.OnSilmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calisanlar_CalisanlarDetay", Storage="_CalisanlarDetays", ThisKey="ID", OtherKey="CalisanID")]
		public EntitySet<CalisanlarDetay> CalisanlarDetays
		{
			get
			{
				return this._CalisanlarDetays;
			}
			set
			{
				this._CalisanlarDetays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CalisanlarDetays(CalisanlarDetay entity)
		{
			this.SendPropertyChanging();
			entity.Calisanlar = this;
		}
		
		private void detach_CalisanlarDetays(CalisanlarDetay entity)
		{
			this.SendPropertyChanging();
			entity.Calisanlar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalisanlarDetay")]
	public partial class CalisanlarDetay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _CalisanID;
		
		private System.Nullable<int> _OdemeId;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private System.Nullable<decimal> _AlacakTutar;
		
		private System.Nullable<decimal> _OdenenTutar;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _SilinmeTarihi;
		
		private System.Nullable<bool> _Silme;
		
		private EntityRef<Calisanlar> _Calisanlar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCalisanIDChanging(System.Nullable<int> value);
    partial void OnCalisanIDChanged();
    partial void OnOdemeIdChanging(System.Nullable<int> value);
    partial void OnOdemeIdChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnAlacakTutarChanging(System.Nullable<decimal> value);
    partial void OnAlacakTutarChanged();
    partial void OnOdenenTutarChanging(System.Nullable<decimal> value);
    partial void OnOdenenTutarChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSilinmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSilinmeTarihiChanged();
    partial void OnSilmeChanging(System.Nullable<bool> value);
    partial void OnSilmeChanged();
    #endregion
		
		public CalisanlarDetay()
		{
			this._Calisanlar = default(EntityRef<Calisanlar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanID", DbType="Int")]
		public System.Nullable<int> CalisanID
		{
			get
			{
				return this._CalisanID;
			}
			set
			{
				if ((this._CalisanID != value))
				{
					if (this._Calisanlar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanID = value;
					this.SendPropertyChanged("CalisanID");
					this.OnCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeId", DbType="Int")]
		public System.Nullable<int> OdemeId
		{
			get
			{
				return this._OdemeId;
			}
			set
			{
				if ((this._OdemeId != value))
				{
					this.OnOdemeIdChanging(value);
					this.SendPropertyChanging();
					this._OdemeId = value;
					this.SendPropertyChanged("OdemeId");
					this.OnOdemeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlacakTutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AlacakTutar
		{
			get
			{
				return this._AlacakTutar;
			}
			set
			{
				if ((this._AlacakTutar != value))
				{
					this.OnAlacakTutarChanging(value);
					this.SendPropertyChanging();
					this._AlacakTutar = value;
					this.SendPropertyChanged("AlacakTutar");
					this.OnAlacakTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdenenTutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> OdenenTutar
		{
			get
			{
				return this._OdenenTutar;
			}
			set
			{
				if ((this._OdenenTutar != value))
				{
					this.OnOdenenTutarChanging(value);
					this.SendPropertyChanging();
					this._OdenenTutar = value;
					this.SendPropertyChanged("OdenenTutar");
					this.OnOdenenTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilinmeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SilinmeTarihi
		{
			get
			{
				return this._SilinmeTarihi;
			}
			set
			{
				if ((this._SilinmeTarihi != value))
				{
					this.OnSilinmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._SilinmeTarihi = value;
					this.SendPropertyChanged("SilinmeTarihi");
					this.OnSilinmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silme", DbType="Bit")]
		public System.Nullable<bool> Silme
		{
			get
			{
				return this._Silme;
			}
			set
			{
				if ((this._Silme != value))
				{
					this.OnSilmeChanging(value);
					this.SendPropertyChanging();
					this._Silme = value;
					this.SendPropertyChanged("Silme");
					this.OnSilmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calisanlar_CalisanlarDetay", Storage="_Calisanlar", ThisKey="CalisanID", OtherKey="ID", IsForeignKey=true)]
		public Calisanlar Calisanlar
		{
			get
			{
				return this._Calisanlar.Entity;
			}
			set
			{
				Calisanlar previousValue = this._Calisanlar.Entity;
				if (((previousValue != value) 
							|| (this._Calisanlar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Calisanlar.Entity = null;
						previousValue.CalisanlarDetays.Remove(this);
					}
					this._Calisanlar.Entity = value;
					if ((value != null))
					{
						value.CalisanlarDetays.Add(this);
						this._CalisanID = value.ID;
					}
					else
					{
						this._CalisanID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Calisanlar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Firmalar")]
	public partial class Firmalar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FirmaAdi;
		
		private string _Telefon;
		
		private System.Nullable<decimal> _Borc;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private System.Nullable<System.DateTime> _SilinmeTarihi;
		
		private System.Nullable<bool> _Silme;
		
		private EntitySet<FirmalarDetay> _FirmalarDetays;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirmaAdiChanging(string value);
    partial void OnFirmaAdiChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnBorcChanging(System.Nullable<decimal> value);
    partial void OnBorcChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnSilinmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSilinmeTarihiChanged();
    partial void OnSilmeChanging(System.Nullable<bool> value);
    partial void OnSilmeChanged();
    #endregion
		
		public Firmalar()
		{
			this._FirmalarDetays = new EntitySet<FirmalarDetay>(new Action<FirmalarDetay>(this.attach_FirmalarDetays), new Action<FirmalarDetay>(this.detach_FirmalarDetays));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaAdi", DbType="NVarChar(150)")]
		public string FirmaAdi
		{
			get
			{
				return this._FirmaAdi;
			}
			set
			{
				if ((this._FirmaAdi != value))
				{
					this.OnFirmaAdiChanging(value);
					this.SendPropertyChanging();
					this._FirmaAdi = value;
					this.SendPropertyChanged("FirmaAdi");
					this.OnFirmaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borc", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Borc
		{
			get
			{
				return this._Borc;
			}
			set
			{
				if ((this._Borc != value))
				{
					this.OnBorcChanging(value);
					this.SendPropertyChanging();
					this._Borc = value;
					this.SendPropertyChanged("Borc");
					this.OnBorcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilinmeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SilinmeTarihi
		{
			get
			{
				return this._SilinmeTarihi;
			}
			set
			{
				if ((this._SilinmeTarihi != value))
				{
					this.OnSilinmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._SilinmeTarihi = value;
					this.SendPropertyChanged("SilinmeTarihi");
					this.OnSilinmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silme", DbType="Bit")]
		public System.Nullable<bool> Silme
		{
			get
			{
				return this._Silme;
			}
			set
			{
				if ((this._Silme != value))
				{
					this.OnSilmeChanging(value);
					this.SendPropertyChanging();
					this._Silme = value;
					this.SendPropertyChanged("Silme");
					this.OnSilmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firmalar_FirmalarDetay", Storage="_FirmalarDetays", ThisKey="ID", OtherKey="FirmaID")]
		public EntitySet<FirmalarDetay> FirmalarDetays
		{
			get
			{
				return this._FirmalarDetays;
			}
			set
			{
				this._FirmalarDetays.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FirmalarDetays(FirmalarDetay entity)
		{
			this.SendPropertyChanging();
			entity.Firmalar = this;
		}
		
		private void detach_FirmalarDetays(FirmalarDetay entity)
		{
			this.SendPropertyChanging();
			entity.Firmalar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FirmalarDetay")]
	public partial class FirmalarDetay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _FirmaID;
		
		private System.Nullable<int> _OdemeId;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _Aciklama;
		
		private System.Nullable<decimal> _AlinanMalTutari;
		
		private System.Nullable<decimal> _OdenenTutar;
		
		private string _OdemeSekli;
		
		private System.Nullable<System.DateTime> _SilinmeTarihi;
		
		private System.Nullable<bool> _Silme;
		
		private EntityRef<Firmalar> _Firmalar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirmaIDChanging(System.Nullable<int> value);
    partial void OnFirmaIDChanged();
    partial void OnOdemeIdChanging(System.Nullable<int> value);
    partial void OnOdemeIdChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnAlinanMalTutariChanging(System.Nullable<decimal> value);
    partial void OnAlinanMalTutariChanged();
    partial void OnOdenenTutarChanging(System.Nullable<decimal> value);
    partial void OnOdenenTutarChanged();
    partial void OnOdemeSekliChanging(string value);
    partial void OnOdemeSekliChanged();
    partial void OnSilinmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSilinmeTarihiChanged();
    partial void OnSilmeChanging(System.Nullable<bool> value);
    partial void OnSilmeChanged();
    #endregion
		
		public FirmalarDetay()
		{
			this._Firmalar = default(EntityRef<Firmalar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaID", DbType="Int")]
		public System.Nullable<int> FirmaID
		{
			get
			{
				return this._FirmaID;
			}
			set
			{
				if ((this._FirmaID != value))
				{
					if (this._Firmalar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFirmaIDChanging(value);
					this.SendPropertyChanging();
					this._FirmaID = value;
					this.SendPropertyChanged("FirmaID");
					this.OnFirmaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeId", DbType="Int")]
		public System.Nullable<int> OdemeId
		{
			get
			{
				return this._OdemeId;
			}
			set
			{
				if ((this._OdemeId != value))
				{
					this.OnOdemeIdChanging(value);
					this.SendPropertyChanging();
					this._OdemeId = value;
					this.SendPropertyChanged("OdemeId");
					this.OnOdemeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(MAX)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlinanMalTutari", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AlinanMalTutari
		{
			get
			{
				return this._AlinanMalTutari;
			}
			set
			{
				if ((this._AlinanMalTutari != value))
				{
					this.OnAlinanMalTutariChanging(value);
					this.SendPropertyChanging();
					this._AlinanMalTutari = value;
					this.SendPropertyChanged("AlinanMalTutari");
					this.OnAlinanMalTutariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdenenTutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> OdenenTutar
		{
			get
			{
				return this._OdenenTutar;
			}
			set
			{
				if ((this._OdenenTutar != value))
				{
					this.OnOdenenTutarChanging(value);
					this.SendPropertyChanging();
					this._OdenenTutar = value;
					this.SendPropertyChanged("OdenenTutar");
					this.OnOdenenTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeSekli", DbType="NVarChar(50)")]
		public string OdemeSekli
		{
			get
			{
				return this._OdemeSekli;
			}
			set
			{
				if ((this._OdemeSekli != value))
				{
					this.OnOdemeSekliChanging(value);
					this.SendPropertyChanging();
					this._OdemeSekli = value;
					this.SendPropertyChanged("OdemeSekli");
					this.OnOdemeSekliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilinmeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SilinmeTarihi
		{
			get
			{
				return this._SilinmeTarihi;
			}
			set
			{
				if ((this._SilinmeTarihi != value))
				{
					this.OnSilinmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._SilinmeTarihi = value;
					this.SendPropertyChanged("SilinmeTarihi");
					this.OnSilinmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silme", DbType="Bit")]
		public System.Nullable<bool> Silme
		{
			get
			{
				return this._Silme;
			}
			set
			{
				if ((this._Silme != value))
				{
					this.OnSilmeChanging(value);
					this.SendPropertyChanging();
					this._Silme = value;
					this.SendPropertyChanged("Silme");
					this.OnSilmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firmalar_FirmalarDetay", Storage="_Firmalar", ThisKey="FirmaID", OtherKey="ID", IsForeignKey=true)]
		public Firmalar Firmalar
		{
			get
			{
				return this._Firmalar.Entity;
			}
			set
			{
				Firmalar previousValue = this._Firmalar.Entity;
				if (((previousValue != value) 
							|| (this._Firmalar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Firmalar.Entity = null;
						previousValue.FirmalarDetays.Remove(this);
					}
					this._Firmalar.Entity = value;
					if ((value != null))
					{
						value.FirmalarDetays.Add(this);
						this._FirmaID = value.ID;
					}
					else
					{
						this._FirmaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Firmalar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GelenOdemeler")]
	public partial class GelenOdemeler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _gelenOdemeId;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _Aciklama;
		
		private System.Nullable<decimal> _Tutar;
		
		private System.Nullable<System.DateTime> _SilinmeTarihi;
		
		private System.Nullable<bool> _Silme;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OngelenOdemeIdChanging(System.Nullable<int> value);
    partial void OngelenOdemeIdChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnSilinmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSilinmeTarihiChanged();
    partial void OnSilmeChanging(System.Nullable<bool> value);
    partial void OnSilmeChanged();
    #endregion
		
		public GelenOdemeler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gelenOdemeId", DbType="Int")]
		public System.Nullable<int> gelenOdemeId
		{
			get
			{
				return this._gelenOdemeId;
			}
			set
			{
				if ((this._gelenOdemeId != value))
				{
					this.OngelenOdemeIdChanging(value);
					this.SendPropertyChanging();
					this._gelenOdemeId = value;
					this.SendPropertyChanged("gelenOdemeId");
					this.OngelenOdemeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(MAX)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilinmeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SilinmeTarihi
		{
			get
			{
				return this._SilinmeTarihi;
			}
			set
			{
				if ((this._SilinmeTarihi != value))
				{
					this.OnSilinmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._SilinmeTarihi = value;
					this.SendPropertyChanged("SilinmeTarihi");
					this.OnSilinmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silme", DbType="Bit")]
		public System.Nullable<bool> Silme
		{
			get
			{
				return this._Silme;
			}
			set
			{
				if ((this._Silme != value))
				{
					this.OnSilmeChanging(value);
					this.SendPropertyChanging();
					this._Silme = value;
					this.SendPropertyChanged("Silme");
					this.OnSilmeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Harcamalar")]
	public partial class Harcamalar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _harcamaid;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private string _Aciklama;
		
		private System.Nullable<decimal> _Tutar;
		
		private System.Nullable<System.DateTime> _SilinmeTarihi;
		
		private System.Nullable<bool> _Silme;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnharcamaidChanging(System.Nullable<int> value);
    partial void OnharcamaidChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnSilinmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSilinmeTarihiChanged();
    partial void OnSilmeChanging(System.Nullable<bool> value);
    partial void OnSilmeChanged();
    #endregion
		
		public Harcamalar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_harcamaid", DbType="Int")]
		public System.Nullable<int> harcamaid
		{
			get
			{
				return this._harcamaid;
			}
			set
			{
				if ((this._harcamaid != value))
				{
					this.OnharcamaidChanging(value);
					this.SendPropertyChanging();
					this._harcamaid = value;
					this.SendPropertyChanged("harcamaid");
					this.OnharcamaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(MAX)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilinmeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SilinmeTarihi
		{
			get
			{
				return this._SilinmeTarihi;
			}
			set
			{
				if ((this._SilinmeTarihi != value))
				{
					this.OnSilinmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._SilinmeTarihi = value;
					this.SendPropertyChanged("SilinmeTarihi");
					this.OnSilinmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silme", DbType="Bit")]
		public System.Nullable<bool> Silme
		{
			get
			{
				return this._Silme;
			}
			set
			{
				if ((this._Silme != value))
				{
					this.OnSilmeChanging(value);
					this.SendPropertyChanging();
					this._Silme = value;
					this.SendPropertyChanged("Silme");
					this.OnSilmeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.İdris")]
	public partial class İdri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private System.Nullable<decimal> _Tutar;
		
		private System.Nullable<System.DateTime> _SilinmeTarihi;
		
		private System.Nullable<bool> _Silme;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnTutarChanging(System.Nullable<decimal> value);
    partial void OnTutarChanged();
    partial void OnSilinmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSilinmeTarihiChanged();
    partial void OnSilmeChanging(System.Nullable<bool> value);
    partial void OnSilmeChanged();
    #endregion
		
		public İdri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(MAX)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilinmeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SilinmeTarihi
		{
			get
			{
				return this._SilinmeTarihi;
			}
			set
			{
				if ((this._SilinmeTarihi != value))
				{
					this.OnSilinmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._SilinmeTarihi = value;
					this.SendPropertyChanged("SilinmeTarihi");
					this.OnSilinmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silme", DbType="Bit")]
		public System.Nullable<bool> Silme
		{
			get
			{
				return this._Silme;
			}
			set
			{
				if ((this._Silme != value))
				{
					this.OnSilmeChanging(value);
					this.SendPropertyChanging();
					this._Silme = value;
					this.SendPropertyChanged("Silme");
					this.OnSilmeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kullanıcılar")]
	public partial class Kullanıcılar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    #endregion
		
		public Kullanıcılar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(50)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this.OnKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciAdi = value;
					this.SendPropertyChanged("KullaniciAdi");
					this.OnKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteriler")]
	public partial class Musteriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _AdSoyad;
		
		private string _Telefon;
		
		private string _BinaAdi;
		
		private System.Nullable<decimal> _Borc;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private System.Nullable<System.DateTime> _OdemeTarihi;
		
		private string _OdemeSekli;
		
		private string _Not;
		
		private System.Nullable<System.DateTime> _SilinmeTarihi;
		
		private System.Nullable<bool> _Silme;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAdSoyadChanging(string value);
    partial void OnAdSoyadChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnBinaAdiChanging(string value);
    partial void OnBinaAdiChanged();
    partial void OnBorcChanging(System.Nullable<decimal> value);
    partial void OnBorcChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnOdemeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOdemeTarihiChanged();
    partial void OnOdemeSekliChanging(string value);
    partial void OnOdemeSekliChanged();
    partial void OnNotChanging(string value);
    partial void OnNotChanged();
    partial void OnSilinmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSilinmeTarihiChanged();
    partial void OnSilmeChanging(System.Nullable<bool> value);
    partial void OnSilmeChanged();
    #endregion
		
		public Musteriler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdSoyad", DbType="NVarChar(150)")]
		public string AdSoyad
		{
			get
			{
				return this._AdSoyad;
			}
			set
			{
				if ((this._AdSoyad != value))
				{
					this.OnAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._AdSoyad = value;
					this.SendPropertyChanged("AdSoyad");
					this.OnAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinaAdi", DbType="NVarChar(150)")]
		public string BinaAdi
		{
			get
			{
				return this._BinaAdi;
			}
			set
			{
				if ((this._BinaAdi != value))
				{
					this.OnBinaAdiChanging(value);
					this.SendPropertyChanging();
					this._BinaAdi = value;
					this.SendPropertyChanged("BinaAdi");
					this.OnBinaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borc", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Borc
		{
			get
			{
				return this._Borc;
			}
			set
			{
				if ((this._Borc != value))
				{
					this.OnBorcChanging(value);
					this.SendPropertyChanging();
					this._Borc = value;
					this.SendPropertyChanged("Borc");
					this.OnBorcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> OdemeTarihi
		{
			get
			{
				return this._OdemeTarihi;
			}
			set
			{
				if ((this._OdemeTarihi != value))
				{
					this.OnOdemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._OdemeTarihi = value;
					this.SendPropertyChanged("OdemeTarihi");
					this.OnOdemeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeSekli", DbType="NVarChar(50)")]
		public string OdemeSekli
		{
			get
			{
				return this._OdemeSekli;
			}
			set
			{
				if ((this._OdemeSekli != value))
				{
					this.OnOdemeSekliChanging(value);
					this.SendPropertyChanging();
					this._OdemeSekli = value;
					this.SendPropertyChanged("OdemeSekli");
					this.OnOdemeSekliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Not]", Storage="_Not", DbType="NVarChar(MAX)")]
		public string Not
		{
			get
			{
				return this._Not;
			}
			set
			{
				if ((this._Not != value))
				{
					this.OnNotChanging(value);
					this.SendPropertyChanging();
					this._Not = value;
					this.SendPropertyChanged("Not");
					this.OnNotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilinmeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SilinmeTarihi
		{
			get
			{
				return this._SilinmeTarihi;
			}
			set
			{
				if ((this._SilinmeTarihi != value))
				{
					this.OnSilinmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._SilinmeTarihi = value;
					this.SendPropertyChanged("SilinmeTarihi");
					this.OnSilinmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silme", DbType="Bit")]
		public System.Nullable<bool> Silme
		{
			get
			{
				return this._Silme;
			}
			set
			{
				if ((this._Silme != value))
				{
					this.OnSilmeChanging(value);
					this.SendPropertyChanging();
					this._Silme = value;
					this.SendPropertyChanged("Silme");
					this.OnSilmeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MusterilerDetay")]
	public partial class MusterilerDetay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MusteriID;
		
		private System.Nullable<int> _OdemeId;
		
		private System.Nullable<decimal> _EklenenTutar;
		
		private System.Nullable<decimal> _OdenenTutar;
		
		private string _OdemeSekli;
		
		private System.DateTime _Tarih;
		
		private string _Aciklama;
		
		private System.Nullable<System.DateTime> _SilinmeTarihi;
		
		private System.Nullable<bool> _Silme;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMusteriIDChanging(System.Nullable<int> value);
    partial void OnMusteriIDChanged();
    partial void OnOdemeIdChanging(System.Nullable<int> value);
    partial void OnOdemeIdChanged();
    partial void OnEklenenTutarChanging(System.Nullable<decimal> value);
    partial void OnEklenenTutarChanged();
    partial void OnOdenenTutarChanging(System.Nullable<decimal> value);
    partial void OnOdenenTutarChanged();
    partial void OnOdemeSekliChanging(string value);
    partial void OnOdemeSekliChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSilinmeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSilinmeTarihiChanged();
    partial void OnSilmeChanging(System.Nullable<bool> value);
    partial void OnSilmeChanged();
    #endregion
		
		public MusterilerDetay()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriID", DbType="Int")]
		public System.Nullable<int> MusteriID
		{
			get
			{
				return this._MusteriID;
			}
			set
			{
				if ((this._MusteriID != value))
				{
					this.OnMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriID = value;
					this.SendPropertyChanged("MusteriID");
					this.OnMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeId", DbType="Int")]
		public System.Nullable<int> OdemeId
		{
			get
			{
				return this._OdemeId;
			}
			set
			{
				if ((this._OdemeId != value))
				{
					this.OnOdemeIdChanging(value);
					this.SendPropertyChanging();
					this._OdemeId = value;
					this.SendPropertyChanged("OdemeId");
					this.OnOdemeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklenenTutar", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> EklenenTutar
		{
			get
			{
				return this._EklenenTutar;
			}
			set
			{
				if ((this._EklenenTutar != value))
				{
					this.OnEklenenTutarChanging(value);
					this.SendPropertyChanging();
					this._EklenenTutar = value;
					this.SendPropertyChanged("EklenenTutar");
					this.OnEklenenTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdenenTutar", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> OdenenTutar
		{
			get
			{
				return this._OdenenTutar;
			}
			set
			{
				if ((this._OdenenTutar != value))
				{
					this.OnOdenenTutarChanging(value);
					this.SendPropertyChanging();
					this._OdenenTutar = value;
					this.SendPropertyChanged("OdenenTutar");
					this.OnOdenenTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeSekli", DbType="NVarChar(50)")]
		public string OdemeSekli
		{
			get
			{
				return this._OdemeSekli;
			}
			set
			{
				if ((this._OdemeSekli != value))
				{
					this.OnOdemeSekliChanging(value);
					this.SendPropertyChanging();
					this._OdemeSekli = value;
					this.SendPropertyChanged("OdemeSekli");
					this.OnOdemeSekliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="DateTime NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(150)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SilinmeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SilinmeTarihi
		{
			get
			{
				return this._SilinmeTarihi;
			}
			set
			{
				if ((this._SilinmeTarihi != value))
				{
					this.OnSilinmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._SilinmeTarihi = value;
					this.SendPropertyChanged("SilinmeTarihi");
					this.OnSilinmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silme", DbType="Bit")]
		public System.Nullable<bool> Silme
		{
			get
			{
				return this._Silme;
			}
			set
			{
				if ((this._Silme != value))
				{
					this.OnSilmeChanging(value);
					this.SendPropertyChanging();
					this._Silme = value;
					this.SendPropertyChanged("Silme");
					this.OnSilmeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
